version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["--replSet", "rs0"]
    networks:
      - mongo-net

  mongo-init:
    image: mongo
    command: "mongosh --eval 'rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"mongo:27017\"}]})'"
    networks:
      - mongo-net
    depends_on:
      - mongo

volumes:
  mongo-data:

networks:
  mongo-net:
